name: Daily Deployment

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Vercel Deploy
      run: |
        curl -X POST -H "Content-Type: application/json" ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
